### ISSUE TITLE
feat: hubs events API for tracking set mutations

### ISSUE THREAD

**Issue by pfletcherhill** [farcasterxyz/hub#71]
### Overview and background
Add an API to the hubs to enable clients to stream events and replicate hub state. A client should be able to connect to a hub and receive updates when new messages are merged into the [hub's sets](https://github.com/farcasterxyz/hub/tree/main/src/sets) (collection of CRDTs that represent the hub's state). The goal is to enable state replication without clients having to implement their own CRDTs.

This feature is important for launching the hub's [v2.0.0 milestone](https://github.com/farcasterxyz/hub/milestone/1), because Merkle will need to run a hub and its backend simultaneously and will need this events API to keep its database in sync with the hub. We expect most hub operators to use this feature to index hub data for easier querying.

### Hub state
Hub state is represented by a collection of CRDTs that we call sets: 
* CastSet - short casts and recasts
* FollowSet - user-to-user follow actions
* ReactionSet - reactions to casts (i.e. likes)
* SignerSet - custody addresses (from IDRegistry events) and delegate signers (Eddsa keys authorized to sign messages on behalf of a user)
* VerificationSet - two-way authorizations between users and external entities (i.e. an Ethereum address)

Each set accepts particular message types that mutate its state when merged:
* CastSet - CastShort, CastRecast, CastRemove
* FollowSet - FollowAdd, FollowRemove
* ReactionSet - ReactionAdd, ReactionRemove
* SignerSet - IDRegistryEvent (from IDRegistry contract), SignerAdd, SignerRemove
* VerificationSet - VerificationEthereumAddress, VerificationRemove

Sets accept messages in any order and multiple times, but we only want to publish events when state changes. Here are examples of expected behavior:
* A CastShort message is received that the CastSet has not seen before and hasn't already been removed. The CastSet merges in the new message and publishes a "new cast" event with the message.
* A FollowAdd message is received that the FollowSet has already removed via a FollowRemove message (the FollowSet is a LWW set, so the remove message has to have a timestamp after the add message). The FollowSet discards the new message and does not publish any events.
* A ReactionAdd message is received that the ReactionSet has already merged in. The ReactionSet discards the duplicate message and does not publish any events.

### Work included in this ticket
* [ ] Gather list of events from all hub sets that can could be used to replicate hub state (i.e. cast added, cast removed, reaction added, signer added, etc)
* [ ] Design our own spec for subscriptions (via RPC or websocket) or integrate something like [graphql-ws](https://github.com/enisdenjo/graphql-ws)
* [ ] Investigate whether/how the events API design is influenced by the choice of a [persistence layer for hubs](https://github.com/farcasterxyz/hub/issues/61) (i.e. leveldb/rocksdb vs postgres)
* [ ] Decide how the events API will relate to the [JSON-RPC API](https://github.com/farcasterxyz/hub/issues/83) (i.e. should we add a JSON-RPC endpoint for retrieving all historical events?)
* [ ] Decide how the events API will relate to the [hub-to-hub sync protocol](https://github.com/farcasterxyz/hub/issues/66)
* [ ] Gather list of edge cases that could cause a service watching these events to get out of sync (i.e. dropped events, etc) with the hubs and address them

### Similar work
* [Geth real-time events](https://geth.ethereum.org/docs/rpc/pubsub) 
* [Solana subscription websocket](https://docs.solana.com/developing/clients/jsonrpc-api#subscription-websocket)
* [Alchemy websockets API](https://docs.alchemy.com/reference/eth-subscribe) 

### Deliverable
When Merkle runs a hub (we will have to implement https://github.com/farcasterxyz/hub/issues/74 beforehand), they should be able to implement a service that opens a websocket connection (or another protocol) via a new endpoint and receives events from the hub. After the hub merges some list of messages (we can agree on a test case), the service should have received a single event for each message that was merged.
